# Generated by Django 5.0.6 on 2024-05-10 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Producer')),
                ('type', models.CharField(choices=[('F', 'Factory'), ('R', 'Retail'), ('E', 'Entrepreneur')], max_length=1, verbose_name='Type')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('number_home', models.PositiveIntegerField(verbose_name='Number of home')),
                ('debt', models.IntegerField(verbose_name='Debt')),
                ('date', models.DateField(auto_now_add=True)),
                ('products', models.ManyToManyField(default=None, to='products.product')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producers.producer')),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
            },
        ),
    ]
